### ISSUE TITLE
Not in npm registry

### ISSUE THREAD

**Issue by JamieMason** [medimatrix/grunt-gitdown#1]
Hey @medimatrix, 
Thanks for making this. I went to install your project using npm according to the README, but it's not in the npm registry.

https://www.npmjs.com/search?q=gitdown

Jamie

**Comment by medimatrix** [comment]
Oops :blush: ! I can't believe I forgot to run `npm publish`!

Thanks for notifying me. [I have now published the module](https://www.npmjs.com/package/grunt-gitdown) and you can install `grunt-gitdown` using `npm install grunt-gitdown`.

**Comment by JamieMason** [comment]
Great, thanks
